development:
  sessions:
    default:
      database: opensea_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: opensea_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0