development:
  sessions:
    default:
      database: cargo-vessel-market_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: cargo-vessel-market_test
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0
